name: Laravel PoW Package Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        laravel-versions: ['8.*', '9.*']
        exclude:
          - php-versions: '7.4'
            laravel-versions: '9.*'

    name: PHP ${{ matrix.php-versions }} - Laravel ${{ matrix.laravel-versions }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel-versions }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction --no-suggest

    - name: Debug Composer Install
      if: failure()
      run: |
        composer --version
        php --version
        php -m
        composer show
        cat composer.json

    - name: Run Tests
      run: vendor/bin/phpunit --coverage-text